CREATE TABLE IF NOT EXISTS ${database}.${prefix}org (
  id BINARY(16) NOT NULL,
  name VARCHAR(255) NOT NULL,
  is_active BIT NOT NULL,
  last_update TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
    NOT NULL,
  PRIMARY KEY (id)
)Engine=InnoDB;
