CREATE TABLE IF NOT EXISTS ${database}.${prefix}user (
  id BINARY(16) NOT NULL,
  name VARCHAR(255) NOT NULL,
  role TINYINT UNSIGNED NOT NULL,
  last_update TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
    NOT NULL,
  PRIMARY KEY (id)
)Engine=InnoDB;
