CREATE TABLE IF NOT EXISTS ${database}.${prefix}org_member (
  org BINARY(16) NOT NULL,
  user BINARY(16) NOT NULL,
  member_class TINYINT UNSIGNED NOT NULL,
  member_role TINYINT UNSIGNED NOT NULL,
  personal_alert BIT NOT NULL,
  last_update TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
    NOT NULL,
  PRIMARY KEY (org, user),
  FOREIGN KEY (org) REFERENCES ${prefix}org (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY (user) REFERENCES ${prefix}user (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)Engine=InnoDB;
