CREATE TABLE IF NOT EXISTS ${database}.${prefix}user_group (
  id BINARY(16) NOT NULL,
  org BINARY(16) NOT NULL,
  label VARCHAR(255) NOT NULL,
  parent BINARY(16),
  last_update TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
    NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (org) REFERENCES ${prefix}org (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY (parent) REFERENCES ${prefix}user_group (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
  )Engine=InnoDB;
